Repository today-they-learned/ttl_front, pull requests merged in 2022-02, with the labels that each got.

#11 프로필편집 페이지 구성
  .eslintrc.js
  package.json
  public/images/facebook.png
  public/images/instagram.png
  public/images/profile.jpg
  public/images/synchronization.png
  public/images/twitter.png
  src/App.js
  src/components/mypage/Grass.js
  src/components/mypage/ProfileEdit.js
  src/components/mypage/ProfileEditStyled.js
  src/components/mypage/ProfileInfo.js
  src/components/mypage/ProfileInfoStyled.js
  src/components/mypage/TilContainer.js
  src/pages/Mypage/Mypage.jsx
  src/pages/index.js
Labels: :bulb: Feature

#25 로그인 API 연결
  .eslintrc.js
  package.json
  src/App.js
  src/components/top_navbar/top_navbar.jsx
  src/config/api.config.js
  src/config/new.js
  src/layouts/desktop_layout.js
  src/pages/Sign/SignIn.jsx
  src/reducers/authentication.js
  src/reducers/index.js
  src/sagas/auth-header.js
  src/sagas/authentication.js
  src/sagas/index.js
  src/store/configureStore.js
  src/utils/produce.util.js
  yarn.lock
Labels: :bulb: Feature, 📬 API

#33 feat: article(single) api 연동
  .eslintrc.js
  package.json
  public/index.html
  src/App.js
  src/config/api.config.js
  src/layouts/desktop_layout.js
  src/pages/Article/Article.jsx
  src/pages/index.js
  src/reducers/article.js
  src/reducers/authentication.js
  src/reducers/index.js
  src/sagas/article.js
  src/sagas/authentication.js
  src/sagas/index.js
Labels: :bulb: Feature, 📬 API

#37 0032 articles api
  src/components/post_card/post_card.jsx
  src/components/post_list/post_list.jsx
  src/reducers/article.js
  src/sagas/article.js
  src/sagas/auth-header.js
Labels: :bulb: Feature, 📬 API

#39 0038 signup api
  package.json
  public/favicon.ico
  public/images/Logo.gif
  src/components/Sign/SignTitle.jsx
  src/components/common/Containers.js
  src/pages/Sign/SignIn.jsx
  src/pages/Sign/SignUp.jsx
  src/reducers/authentication.js
  src/sagas/authentication.js
  yarn.lock
Labels: :bulb: Feature, 📬 API

#27 글 작성 및 수정 에디터
  package-lock.json
  package.json
  src/App.js
  src/components/PostEditorForm/PostEditorForm.jsx
  src/components/PostEditorForm/toastui-editor.css
  src/components/PostModal/PostModal.jsx
  src/components/PostModal/PostModalStyle.js
  src/components/post_list/post_list.jsx
  src/components/top_navbar/top_navbar.jsx
  src/constants/color.constant.js
  src/layouts/desktop_layout.js
  yarn.lock
Labels: :bulb: Feature

#45 Feat: article 페이지 추가
  package-lock.json
  package.json
  public/images/missing.png
  src/components/Article/Comment.jsx
  src/components/Article/FloatMenu.jsx
  src/components/common/Containers.js
  src/components/mobile_navbar/mobile_navbar.jsx
  src/components/post_card/post_card.jsx
  src/components/post_card/post_card_styled.js
  src/components/post_list/post_list.jsx
  src/components/top_navbar/top_navbar.jsx
  src/constants/color.constant.js
  src/hooks/useDate.js
  src/layouts/responsive.layout.js
  src/pages/Article/Article.jsx
  src/reducers/article.js
  src/reducers/comment.js
  src/reducers/index.js
  src/sagas/article.js
  src/sagas/auth-header.js
  src/sagas/authentication.js
  src/sagas/comment.js
  src/sagas/index.js
  src/styles/GlobalStyles.js
  src/styles/media.js
  yarn.lock
Labels: :bulb: Feature, 📬 API

#89 mobile: 검색 기능 추가, desktop: 검색 애니메이션 수정
  src/components/Navbar/DesktopNavbar.jsx
  src/components/Sidebar/MobileSidebar.jsx
Labels: :bulb: Feature, 🧹 Refactor, 👀 In review

#94 구글 자동번역 기능 해제
  public/index.html
Labels: :bug: Bug, 👏 Merge Needed

#104 #89 #94 #102 pr의 내용을 배포합니다.
  public/index.html
  src/components/Mypage/ProfileInfo.jsx
  src/components/Navbar/DesktopNavbar.jsx
  src/components/Sidebar/MobileSidebar.jsx
Labels: :earth_asia: Deploy

#106 bug: 태그 길어질 때 ui 깨짐 현상 해결
  src/components/PostList/PostCard.jsx
  src/components/PostList/PostCardStyled.js
  src/components/PostList/PostList.jsx
Labels: :bug: Bug, 👀 In review

#115 bug: 태그 길어질 때 ui 깨짐 현상 해결 (#106) 배포
  src/components/PostList/PostCard.jsx
  src/components/PostList/PostCardStyled.js
  src/components/PostList/PostList.jsx
Labels: :earth_asia: Deploy
